#!/usr/bin/env python3
"""Regenerate .pages.yml from i18n/en.json + scripts/cms_field_meta.json.

The CMS config must list every key in every language file, because Pages CMS
rebuilds a JSON file from the fields it knows about on save -- an undeclared
key is dropped. The single source of truth for the key list is i18n/en.json;
labels and string/text types live in scripts/cms_field_meta.json.

Run after adding or removing i18n keys:

    python3 scripts/generate_pages_yml.py

Field names are the literal JSON keys. They must NOT contain dots: Pages CMS's
editor treats a dotted field name as a nested object path while the serializer
reads it as a literal key, so edits to dotted keys are silently discarded
(see the commit that introduced this script). Keys are therefore underscore-
flattened ("home.h1" -> "home_h1").
"""
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LABELS = {
    "en": "English",
    "zh": "中文",
    "fr": "Français",
    "es": "Español",
    "ru": "Русский",
}


def main():
    en_path = os.path.join(HERE, "i18n", "en.json")
    meta_path = os.path.join(HERE, "scripts", "cms_field_meta.json")
    out_path = os.path.join(HERE, ".pages.yml")

    with open(en_path, encoding="utf-8") as fh:
        keys = list(json.load(fh))
    with open(meta_path, encoding="utf-8") as fh:
        meta = json.load(fh)

    lines = [
        "# Pages CMS content model for epidetective.com",
        "#",
        "# Generated by scripts/generate_pages_yml.py -- do not hand-edit.",
        "# Field names are literal JSON keys (dots replaced with underscores so the",
        "# CMS editor round-trips correctly).",
        "",
        "media: assets",
        "",
        "content:",
    ]
    for lang, label in LABELS.items():
        lines += [
            "  - name: %s" % lang,
            '    label: "%s"' % label,
            "    type: file",
            "    path: i18n/%s.json" % lang,
            "    format: json",
            "    fields:",
        ]
        for key in keys:
            m = meta.get(key, {"label": key, "type": "string"})
            lines.append('      - name: "%s"' % key)
            lines.append('        label: "%s"' % m["label"].replace('"', '\\"'))
            lines.append("        type: %s" % m["type"])
        lines.append("")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")
    print("Wrote %s (%d fields x %d languages)." % (out_path, len(keys), len(LABELS)))


if __name__ == "__main__":
    main()
